### ISSUE TITLE
Focusable elments in the background are technically still be focusable

### ISSUE THREAD

**Issue by OddDev** [activenode/react-use-focus-trap#10]
We do not rely on making focusable elements in the background non-focusable. We rather make them unreachable by the default "tab key pressed"-event behavior.
This introduces two major issues:
1. Focusing stuff through other methods than pressing tab still works (e.g. through a browser extension like Vinium)
2. It breaks the Developer Tools (tab index does not show the "real" tab index)

**Comment by activenode** [comment]
Thanks for bringing this issue in. Can we have some sources on if this is an issue or not? I'd be seeing issues in actively preventing this as it could be annoying:

I am in DevTools, I focus something in the background for whatever debugging reasons: Doesn't work because the focus trap tries to enforce being forever locked within the Modal. 

So I'd like to include some more opinions and facts here that we can base this feature on. From a short peek of the docs there is no requirement of making bg completely non-focusable. But I can't be pinpointed on that in this very moment.

**Comment by activenode** [comment]
Since the goal of this package is to provide a11y support we cannot ensure that someone who intentionally focuses other things on the Web Page will be unable to do so. Imagine I'd be using the Inspector to do so and this package would immediately detect that and change it back to the modal. That would be really intrusive. 

If another tool such as vimium induces this then it would be an issue in the vimium tool not part of this standard-based tool. Hence closing :) Thanks!
