### ISSUE TITLE
Do not assume the key to focus change

### ISSUE THREAD

**Issue by OddDev** [activenode/react-use-focus-trap#9]
Currently, we heavily rely on the assumption that tab is used to cycle forward through the focusable elements and shift + tab is used for the opposite direction.
We should rather have a solution tied to the "change focus" in favor of the "tab pressed" event.

**Comment by activenode** [comment]
I like the idea. I had something like this in mind when creating this library. 

This requires:

- What's the cheapest thing to listen to? (`on('focus')@document` ?)
- Wouldn't that introduce a problem? Maybe and probably not because we can prevent the focus change. But what I have in mind is a "flash of focus" which I would like to avoid because it could be annoying and irritating for a11y users.

**Comment by activenode** [comment]
Detecting the focus on the whole page would be again an intrusive thing to do.

Here is a valid use-case leaving the modal focus without leaving the Modal: In a11y sometimes there are additional menus to be opened e.g. context menus that overlay from a portal. Those can become active by programmatically focusing them (whilst having the modal trap). So basically this wouldn't be possible anymore if we would actively "seek" the focus to achieve the solution for the proposed issue.

Also if you use a different key for focusing then it is a problem of keymapping? Or in other words: If someone uses "cmd + s" to "press enter" via browser extension then the extension itself should still send enter. So I think we shouldnt solve the problem of an extension?

**Comment by activenode** [comment]
Closing this as of the mentioned reasons
